name: 'print-devices'

on:
  workflow_dispatch:

jobs:
  print:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os:
          - macos-10.15
          - macos-11.0
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - run: npm run print_devices -- devices-${{ matrix.os }}.md
      - run: cat devices-${{ matrix.os }}.md
